language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
services:
  - postgresql

before_script:
  - psql -c "create database test_env ;" -U postgres
  - psql -c "CREATE USER champs WITH PASSWORD 'nomad';" -U postgres
  - npm i
script: 
  - npm test
after_success:
  - npm run coveralls
