import Hasher from '../../helpers/passwordHashHelper';

const up = (queryInterface) => queryInterface.bulkInsert(
  'Users',
  [{
    firstname: 'amAmanager',
    lastname: 'dontmodifieme',
    email: 'dummydata01@example.com',
    username: 'dummydata01',
    password: Hasher.hashPassword('123456789'),
    isVerified: true,
    role: 'Manager',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'dummy',
    lastname: 'Data',
    email: 'dummydata02@example.com',
    username: 'dummyData02',
    password: Hasher.hashPassword('123456789'),
    isVerified: false,
    role: 'Manager',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'dummy3',
    lastname: 'Data',
    email: 'dummydata03@example.com',
    username: 'dummyData03',
    password: Hasher.hashPassword('123456789'),
    isVerified: true,
    role: 'Super Administrator',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'dummy4',
    lastname: 'Data',
    email: 'notsuperadmin@example.com',
    username: 'dummyData04',
    password: Hasher.hashPassword('123456789'),
    isVerified: true,
    role: 'Manager',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'Dumebi',
    lastname: 'Hiu',
    email: 'dev@example.com',
    username: 'dummyData05',
    password: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    role: 'Requester',
    lineManager: 1,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'Dumebi',
    lastname: 'Hiu',
    email: 'champs@gmail.com',
    username: 'dummyData06',
    password: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    role: 'Requester',
    lineManager: 1,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'ag',
    lastname: 'gy',
    email: 'aggyreina@gmail.com',
    username: 'dummyData02',
    password: 'aggy',
    role: 'Requester',
    lineManager: 1,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'chris',
    lastname: 'meme',
    email: 'chrischris@example.com',
    username: 'chrisMeme',
    password: Hasher.hashPassword('123456789'),
    role: 'Requester',
    lineManager: 1,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstname: 'ag',
    lastname: 'gy',
    email: 'aggy@gmail.com',
    username: 'dummyData022',
    password: Hasher.hashPassword('123456'),
    role: 'Requester',
    lineManager: 1,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  ], {},
);
const down = (queryInterface) => queryInterface.bulkDelete('Users', null, {});

export {
  up,
  down
};
