import PasswordHelper from '../../helpers/passwordHelper';

const up = (queryInterface) => queryInterface.bulkInsert(
  'Users',
  [{
    firstname: 'amAmanager',
    lastname: 'dontmodifieme',
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    email: 'dummydata01@example.com',
    username: 'dummydata01',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    isVerified: true,
    role: 'Manager',
    authType: 'google',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'dummy',
    lastname: 'Data',
    email: 'dummydata02@example.com',
    username: 'dummyData02',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    isVerified: false,
    role: 'Manager',
    authType: 'google',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'dummy3',
    lastname: 'Data',
    email: 'dummydata03@example.com',
    username: 'dummyData03',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    isVerified: true,
    role: 'Super Administrator',
    authType: 'google',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'dummy4',
    lastname: 'Data',
    email: 'notsuperadmin@example.com',
    username: 'dummyData04',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    isVerified: true,
    role: 'Manager',
    authType: 'google',
    lineManager: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'Dumebi',
    lastname: 'Hiu',
    email: 'dev@example.com',
    username: 'dummyData05',
    password: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    confirmPassword: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    role: 'Requester',
    authType: 'google',
    lineManager: 1,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'Dumebi',
    lastname: 'Hiu',
    email: 'champs@gmail.com',
    username: 'dummyData06',
    password: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    confirmPassword: '$2b$10$tDKZuepZakRJQ7wPmtTO9uD2aOd7CdD.R9QNBA1nt45cOTEF1C4rC',
    role: 'Requester',
    authType: 'google',
    lineManager: 1,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'ag',
    lastname: 'gy',
    email: 'aggyreina@gmail.com',
    username: 'dummyData02',
    password: PasswordHelper.hashPassword('aggy'),
    confirmPassword: PasswordHelper.hashPassword('aggy'),
    role: 'Requester',
    authType: 'google',
    lineManager: 1,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'chris',
    lastname: 'meme',
    email: 'chrischris@example.com',
    username: 'chrisMeme',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    role: 'Requester',
    authType: 'google',
    lineManager: 1,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    googleId: '',
    facebookId: '',
    profileImage: 'https://mcdn.wallpapersafari.com/medium/57/33/UW0jhS.jpg',
    firstname: 'Dumebi',
    lastname: 'Hiu',
    email: 'nogiveup119@gmail.com',
    username: 'dummyData06',
    password: PasswordHelper.hashPassword('123456789'),
    confirmPassword: PasswordHelper.hashPassword('123456789'),
    role: 'Supplier',
    authType: 'local',
    lineManager: 1,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  ], {},
);
const down = (queryInterface) => queryInterface.bulkDelete('Users', null, {});

export { up, down };
